### ISSUE TITLE
renterd generates incorrect config file according to user input at config time

### ISSUE THREAD

**Issue by bschwand** [SiaFoundation/renterd#1201]
### Current Behavior

using the interactive renterd config, while specifying to use sqlite as backend, the resulting renterd.yml includes mysql configuration instead

### Expected Behavior

renterd.yml should contain setting for sqlite, not mysql

### Steps to Reproduce

I tested this with a local hand build of renterd testnet which was done like this:
```
sia: ~/sia/renterd] # export BUILD_TAGS='netgo testnet'
sia: ~/sia/renterd] # CGO_ENABLED=1 go build -ldflags='-s -w -linkmode external -extldflags "-static"' -tags="${BUILD_TAGS}" ./cmd/renterd

```
then ran renterd to configure it
```
sia: ~/sia/renterd]# cd /var/lib/renterd/
sia: /var/lib/renterd]# /root/sia/renterd/renterd config

```
some interactions...

```
Would you like to configure advanced settings? (yes/no): yes

Advanced settings are used to configure the renter's behavior.
You can leave these settings blank to use the defaults.

The HTTP address is used to serve the renter's admin API.
The admin API is used to configure the renter.
It should not be exposed to the public internet without setting up a reverse proxy.
HTTP Address (currently "localhost:9880"):

The gateway address is used to exchange blocks with other nodes in the Sia network
It should be exposed publicly to improve the renter's connectivity.
Gateway Address (currently ":9881"):

The database is used to store the renter's metadata.
The embedded SQLite database is recommended for small (< 50TB), single-user setups. Choose this for the easiest setup.
MySQL database is recommended for larger (> 50TB) or multi-user setups. MySQL requires a separate MySQL server to connect to.
Which data store would you like to use? (mysql/sqlite): sqlite

```
then I can see
```
sia: /var/lib/renterd]# tail renterd.yml
    revisionSubmissionBuffer: 144
    scannerInterval: 24h0m0s
    scannerBatchSize: 1000
    scannerNumThreads: 100
    migratorParallelSlabsPerWorker: 1
database:
    mysql:
        user: renterd
        database: renterd
        metricsDatabase: renterd_metrics

```

### Version

commit 10db30005e6185474a55dc1cc09731015b119bf9 (HEAD -> dev, origin/dev, origin/HEAD)

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

FreeBSD 14

### Autopilot Config

N/A

### Bus Config

N/A

### Contract Set Contracts

N/A
