### ISSUE TITLE
renterd fails to connect to peers in docker

### ISSUE THREAD

**Issue by lukehmcc** [SiaFoundation/renterd#1902]
### Current Behavior

As doccumented in the discord, if I set up a `renterd` node with the default docker config:

```yaml
version: "3.9"
services:
  renterd:
    image: ghcr.io/siafoundation/renterd:master
    environment:
      - RENTERD_SEED=put your seed here
      - RENTERD_API_PASSWORD=test
    ports:
      - 9980:9980
      - 9981:9981
      - 8080:8080
    volumes:
      - ./data:/data
    restart: unless-stopped
    stop_grace_period: 5m
```

Peers would refuse to connect, even vetted functional peers. Thus the node would never sync.

I had to swap the `ports` section for `network_mode: host`. Once I did that it worked fine.

### Expected Behavior

The default configuration should work. Either peers should be connectable in the container, or the network mode should be set to host.

### Steps to Reproduce

1. Have a function debian system with docker-ce.
2. Copy and paste the default docker compose (and change api key & seed)
3. `docker compose up -d && docker compose logs -f` you'll see autopilot never connects to peers.

### Version

v2.2.1

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

debian 12

### Autopilot Config

covalent@colocross1:~/docker/renterd$ curl -u ":xxx" http://localhost:9980/api/bus/autopilot 404 page not found

### Bus Config

covalent@colocross1:~/docker/renterd$ curl -u ":xxx" http://localhost:9980/api/bus/settings/gouging curl -u ":xxx" http://localhost:9980/api/bus/settings/pinned curl -u ":xxx" http://localhost:9980/api/bus/settings/upload 404 page not found 404 page not found 404 page not found
